### Exploração de Dataset Simples

#### "MICRODADOS DO ENEM 2024" / "RESULTADOS_2024"

In [1]:
import pandas as pd
print(pd.__version__)

3.0.5

In [2]:
df = pd.read_csv(
    "../../../data/raw/enem/microdados_enem_2024/DADOS/RESULTADOS_2024.csv",
    sep=";",
    encoding="latin-1"
)

In [3]:
df.shape

(4332944, 42)

In [4]:
df.head()

,NU_SEQUENCIAL,NU_ANO,CO_ESCOLA,CO_MUNICIPIO_ESC,NO_MUNICIPIO_ESC,CO_UF_ESC,SG_UF_ESC,TP_DEPENDENCIA_ADM_ESC,TP_LOCALIZACAO_ESC,TP_SIT_FUNC_ESC,...,TX_GABARITO_CH,TX_GABARITO_LC,TX_GABARITO_MT,TP_STATUS_REDACAO,NU_NOTA_COMP1,NU_NOTA_COMP2,NU_NOTA_COMP3,NU_NOTA_COMP4,NU_NOTA_COMP5,NU_NOTA_REDACAO
0,206403,2024,23052929.0,2301406.0,Aratuba,23.0,CE,2.0,1.0,1.0,...,CECEBEBCDBADDEBBABCDCAECEDADBAEABEADCEDADACBC,CAAAECDDDAECBECEDDCBDEDDCECBDCBCEADBBDBDDCBEDA...,CECEBEDADCAADECDBBCEBDCCCACABBABBADDDCEADBBCE,1.0,80.0,60.0,60.0,80.0,20.0,300.0
1,3604651,2024,42103770.0,4218004.0,Tijucas,42.0,SC,4.0,1.0,1.0,...,DADABCDCECEDEBBBEBCDBADACBCADCEBEADBAECAECEDA,AACEADDDACDADECBBDBEEBDDECCBEDDCADBBDEBCEBDCEC...,DBCECEACADABBECBEDADCCDCCABBBCECEBCEADABBADDD,1.0,160.0,200.0,200.0,180.0,180.0,920.0
2,1461268,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,CAEDBADBEBCCEDADBAEACBCADCEDEBBEBACECEABCDDAD,EAAACDDCDADDCBDEECEECBDCDADEEBCBEBADBCEBDBDDDD...,ABBABBADDDBBCECEADCEBCCCDBADCBEDAECADACDBCECE,1.0,120.0,120.0,40.0,120.0,80.0,480.0
3,4301058,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,ACBCADCEDBAECEDADBADBEBCDADABCDEABCAEDEBBCECE,AACEADACDDCBEDADEEBDDBDBBCEECBDCBADDDCBDEDDCEC...,CEBCEADBBCEADDDABBABBCCDCCECEDBACADECABEDADCB,1.0,140.0,200.0,160.0,160.0,80.0,740.0
4,3148322,2024,21150354.0,2100436.0,Alto Alegre do Maranhão,21.0,MA,2.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4332944 entries, 0 to 4332943
Data columns (total 42 columns):
 #   Column                  Dtype
---  ------                  -----
 0   NU_SEQUENCIAL           int64
 1   NU_ANO                  int64
 2   CO_ESCOLA               float64
 3   CO_MUNICIPIO_ESC        float64
 4   NO_MUNICIPIO_ESC        str
 5   CO_UF_ESC               float64
 6   SG_UF_ESC               str
 7   TP_DEPENDENCIA_ADM_ESC  float64
 8   TP_LOCALIZACAO_ESC      float64
 9   TP_SIT_FUNC_ESC         float64
 10  CO_MUNICIPIO_PROVA      int64
 11  NO_MUNICIPIO_PROVA      str
 12  CO_UF_PROVA             int64
 13  SG_UF_PROVA             str
 14  TP_PRESENCA_CN          int64
 15  TP_PRESENCA_CH          int64
 16  TP_PRESENCA_LC          int64
 17  TP_PRESENCA_MT          int64
 18  CO_PROVA_CN             float64
 19  CO_PROVA_CH             float64
 20  CO_PROVA_LC             float64
 21  CO_PROVA_MT             float64
 22  NU_NOTA_CN              float64
 23  NU_NOTA_CH              float64
 24  NU_NOTA_LC              float64
 25  NU_NOTA_MT              float64
 26  TX_RESPOSTAS_CN         str
 27  TX_RESPOSTAS_CH         str
 28  TX_RESPOSTAS_LC         str
 29  TX_RESPOSTAS_MT         str
 30  TP_LINGUA               int64
 31  TX_GABARITO_CN          str
 32  TX_GABARITO_CH          str
 33  TX_GABARITO_LC          str
 34  TX_GABARITO_MT          str
 35  TP_STATUS_REDACAO       float64
 36  NU_NOTA_COMP1           float64
 37  NU_NOTA_COMP2           float64
 38  NU_NOTA_COMP3           float64
 39  NU_NOTA_COMP4           float64
 40  NU_NOTA_COMP5           float64
 41  NU_NOTA_REDACAO         float64
dtypes: float64(21), int64(9), str(12)
memory usage: 1.4 GB

In [6]:
df.describe(include="all")

,NU_SEQUENCIAL,NU_ANO,CO_ESCOLA,CO_MUNICIPIO_ESC,NO_MUNICIPIO_ESC,CO_UF_ESC,SG_UF_ESC,TP_DEPENDENCIA_ADM_ESC,TP_LOCALIZACAO_ESC,TP_SIT_FUNC_ESC,...,TX_GABARITO_CH,TX_GABARITO_LC,TX_GABARITO_MT,TP_STATUS_REDACAO,NU_NOTA_COMP1,NU_NOTA_COMP2,NU_NOTA_COMP3,NU_NOTA_COMP4,NU_NOTA_COMP5,NU_NOTA_REDACAO
count,4.332944e+06,4332944.0,1.565797e+06,1.565797e+06,1565797,1.565797e+06,1565797,1.565797e+06,1.565797e+06,1565797.0,...,3167955,3167955,3004981,3.167955e+06,3.167955e+06,3.167955e+06,3.167955e+06,3.167955e+06,3.167955e+06,3.167955e+06
unique,NaN,NaN,NaN,NaN,5289,NaN,27,NaN,NaN,NaN,...,4,5,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,NaN,NaN,NaN,São Paulo,NaN,SP,NaN,NaN,NaN,...,ACBCADCEDBAECEDADBADBEBCDADABCDEABCAEDEBBCECE,AACEADACDDCBEDADEEBDDBDBBCEECBDCBADDDCBDEDDCEC...,CEBCEADBBCEADDDABBABBCCDCCECEDBACADECABEDADCB,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,NaN,NaN,NaN,68157,NaN,285199,NaN,NaN,NaN,...,804316,803027,762924,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,2.166472e+06,2024.0,3.183945e+07,3.146948e+06,NaN,3.131772e+01,NaN,2.298083e+00,1.049653e+00,1.0,...,NaN,NaN,NaN,1.198513e+00,1.196365e+02,1.445770e+02,1.179561e+02,1.289017e+02,1.135219e+02,6.245932e+02
std,1.250813e+06,0.0,1.042224e+07,9.964620e+05,NaN,9.935772e+00,NaN,7.950171e-01,2.172264e-01,0.0,...,NaN,NaN,NaN,9.216038e-01,3.757981e+01,4.799929e+01,4.247041e+01,4.594068e+01,6.253214e+01,2.163426e+02
min,1.000000e+00,2024.0,1.100006e+07,1.100015e+06,NaN,1.100000e+01,NaN,1.000000e+00,1.000000e+00,1.0,...,NaN,NaN,NaN,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,1.083237e+06,2024.0,2.502085e+07,2.500502e+06,NaN,2.500000e+01,NaN,2.000000e+00,1.000000e+00,1.0,...,NaN,NaN,NaN,1.000000e+00,1.000000e+02,1.200000e+02,1.000000e+02,1.200000e+02,8.000000e+01,5.200000e+02
50%,2.166472e+06,2024.0,3.120025e+07,3.148103e+06,NaN,3.100000e+01,NaN,2.000000e+00,1.000000e+00,1.0,...,NaN,NaN,NaN,1.000000e+00,1.200000e+02,1.600000e+02,1.200000e+02,1.200000e+02,1.200000e+02,6.400000e+02
75%,3.249708e+06,2024.0,3.556817e+07,3.550308e+06,NaN,3.500000e+01,NaN,2.000000e+00,1.000000e+00,1.0,...,NaN,NaN,NaN,1.000000e+00,1.400000e+02,1.800000e+02,1.400000e+02,1.600000e+02,1.600000e+02,7.800000e+02
max,4.332944e+06,2024.0,6.002939e+07,5.300108e+06,NaN,5.300000e+01,NaN,4.000000e+00,2.000000e+00,1.0,...,NaN,NaN,NaN,9.000000e+00,2.000000e+02,2.000000e+02,2.000000e+02,2.000000e+02,2.000000e+02,1.000000e+03