### Exploração de Dataset Simples

#### "MICRODADOS DO ENEM 2024" / "PARTICIPANTES_2024"

In [1]:
import pandas as pd
print(pd.__version__)

3.0.5

In [2]:
df = pd.read_csv(
    "../../../data/raw/enem/microdados_enem_2024/DADOS/PARTICIPANTES_2024.csv",
    sep=";",
    encoding="latin-1"
)

In [3]:
df.shape

(4332944, 38)

In [4]:
df.head()

,NU_INSCRICAO,NU_ANO,TP_FAIXA_ETARIA,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,TP_ANO_CONCLUIU,TP_ENSINO,...,Q014,Q015,Q016,Q017,Q018,Q019,Q020,Q021,Q022,Q023
0,210062064233,2024,5,F,1,1,1,1,3,NaN,...,A,B,B,B,D,A,B,B,E,A
1,210062064234,2024,11,F,1,1,1,1,10,NaN,...,A,A,A,A,B,A,B,A,C,A
2,210062064235,2024,11,F,1,1,1,1,9,NaN,...,A,B,B,B,D,B,B,A,D,A
3,210062064236,2024,3,F,1,3,1,2,0,1.0,...,A,B,A,A,A,A,B,A,D,A
4,210062064237,2024,16,M,3,1,1,1,18,NaN,...,A,A,A,A,B,A,B,A,B,A

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4332944 entries, 0 to 4332943
Data columns (total 38 columns):
 #   Column              Dtype
---  ------              -----
 0   NU_INSCRICAO        int64
 1   NU_ANO              int64
 2   TP_FAIXA_ETARIA     int64
 3   TP_SEXO             str
 4   TP_ESTADO_CIVIL     int64
 5   TP_COR_RACA         int64
 6   TP_NACIONALIDADE    int64
 7   TP_ST_CONCLUSAO     int64
 8   TP_ANO_CONCLUIU     int64
 9   TP_ENSINO           float64
 10  IN_TREINEIRO        int64
 11  CO_MUNICIPIO_PROVA  int64
 12  NO_MUNICIPIO_PROVA  str
 13  CO_UF_PROVA         int64
 14  SG_UF_PROVA         str
 15  Q001                str
 16  Q002                str
 17  Q003                str
 18  Q004                str
 19  Q005                int64
 20  Q006                str
 21  Q007                str
 22  Q008                str
 23  Q009                str
 24  Q010                str
 25  Q011                str
 26  Q012                str
 27  Q013                str
 28  Q014                str
 29  Q015                str
 30  Q016                str
 31  Q017                str
 32  Q018                str
 33  Q019                str
 34  Q020                str
 35  Q021                str
 36  Q022                str
 37  Q023                str
dtypes: float64(1), int64(12), str(25)
memory usage: 1.2 GB

In [6]:
df.describe(include="all")

,NU_INSCRICAO,NU_ANO,TP_FAIXA_ETARIA,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,TP_ANO_CONCLUIU,TP_ENSINO,...,Q014,Q015,Q016,Q017,Q018,Q019,Q020,Q021,Q022,Q023
count,4.332944e+06,4332944.0,4.332944e+06,4332944,4.332944e+06,4.332944e+06,4.332944e+06,4.332944e+06,4.332944e+06,1.545882e+06,...,4332944,4332944,4332943,4332944,4332944,4332942,4332944,4332944,4332944,4332944
unique,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,...,2,2,2,2,4,2,2,5,5,6
top,NaN,NaN,NaN,F,NaN,NaN,NaN,NaN,NaN,NaN,...,A,B,A,A,B,A,B,A,D,A
freq,NaN,NaN,NaN,2624621,NaN,NaN,NaN,NaN,NaN,NaN,...,3776744,2647304,2340250,3311518,2769413,3442684,3799437,2128452,1246495,3282783
mean,2.100643e+11,2024.0,4.803929e+00,NaN,1.034212e+00,2.042669e+00,1.030515e+00,1.780171e+00,2.263291e+00,1.006213e+00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,1.279403e+06,0.0,3.825449e+00,NaN,4.085476e-01,1.004142e+00,2.281566e-01,7.716867e-01,4.510310e+00,7.857914e-02,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,2.100621e+11,2024.0,1.000000e+00,NaN,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,1.000000e+00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,2.100632e+11,2024.0,2.000000e+00,NaN,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,1.000000e+00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,2.100643e+11,2024.0,3.000000e+00,NaN,1.000000e+00,2.000000e+00,1.000000e+00,2.000000e+00,0.000000e+00,1.000000e+00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,2.100654e+11,2024.0,6.000000e+00,NaN,1.000000e+00,3.000000e+00,1.000000e+00,2.000000e+00,2.000000e+00,1.000000e+00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,2.100665e+11,2024.0,2.000000e+01,NaN,4.000000e+00,5.000000e+00,4.000000e+00,4.000000e+00,1.800000e+01,2.000000e+00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN