### Exploração de Dataset Simples

#### "MICRODADOS DO ENEM 2024" / "ITENS_PROVA_2024"

In [1]:
import pandas as pd
print(pd.__version__)

3.0.5

In [2]:
df = pd.read_csv(
    "../../../data/raw/enem/microdados_enem_2024/DADOS/ITENS_PROVA_2024.csv",
    sep=";",
    encoding="latin-1"
)

In [3]:
df.shape

(5550, 14)

In [4]:
df.head()

,CO_POSICAO,SG_AREA,CO_ITEM,TX_GABARITO,CO_HABILIDADE,IN_ITEM_ABAN,TX_MOTIVO_ABAN,NU_PARAM_A,NU_PARAM_B,NU_PARAM_C,TX_COR,CO_PROVA,TP_LINGUA,IN_ITEM_ADAPTADO
0,6,LC,150678,E,20,0,NaN,3.15898,0.16783,0.17207,AZUL,1395,NaN,0
1,7,LC,14475,D,1,0,NaN,2.36980,-0.23487,0.12324,AZUL,1353,NaN,0
2,7,LC,14475,D,1,0,NaN,2.36980,-0.23487,0.12324,AZUL,1441,NaN,0
3,7,LC,16575,A,16,0,NaN,3.04396,2.33757,0.08577,AMARELA,1354,NaN,0
4,7,LC,16575,A,16,0,NaN,3.04396,2.33757,0.08577,AMARELA,1442,NaN,0

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5550 entries, 0 to 5549
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CO_POSICAO        5550 non-null   int64
 1   SG_AREA           5550 non-null   str
 2   CO_ITEM           5550 non-null   int64
 3   TX_GABARITO       5550 non-null   str
 4   CO_HABILIDADE     5550 non-null   int64
 5   IN_ITEM_ABAN      5550 non-null   int64
 6   TX_MOTIVO_ABAN    30 non-null     str
 7   NU_PARAM_A        5520 non-null   float64
 8   NU_PARAM_B        5520 non-null   float64
 9   NU_PARAM_C        5520 non-null   float64
 10  TX_COR            5550 non-null   str
 11  CO_PROVA          5550 non-null   int64
 12  TP_LINGUA         300 non-null    float64
 13  IN_ITEM_ADAPTADO  5550 non-null   int64
dtypes: float64(4), int64(6), str(4)
memory usage: 607.2 KB

In [6]:
df.describe(include="all")

,CO_POSICAO,SG_AREA,CO_ITEM,TX_GABARITO,CO_HABILIDADE,IN_ITEM_ABAN,TX_MOTIVO_ABAN,NU_PARAM_A,NU_PARAM_B,NU_PARAM_C,TX_COR,CO_PROVA,TP_LINGUA,IN_ITEM_ADAPTADO
count,5550.000000,5550,5550.000000,5550,5550.000000,5550.000000,30,5520.000000,5520.000000,5520.000000,5550,5550.000000,300.000000,5550.000000
unique,NaN,4,NaN,6,NaN,NaN,2,NaN,NaN,NaN,8,NaN,NaN,NaN
top,NaN,LC,NaN,D,NaN,NaN,Algoritmo não convergiu,NaN,NaN,NaN,VERDE,NaN,NaN,NaN
freq,NaN,1500,NaN,1188,NaN,NaN,18,NaN,NaN,NaN,1665,NaN,NaN,NaN
mean,88.135135,NaN,110096.268108,NaN,15.063243,0.005405,NaN,2.232899,1.147142,0.181006,NaN,1383.980180,0.500000,0.300000
std,53.186867,NaN,39284.522516,NaN,8.494439,0.073329,NaN,0.874401,0.973074,0.071730,NaN,36.736307,0.500835,0.458299
min,1.000000,NaN,7685.000000,NaN,1.000000,0.000000,NaN,0.207040,-0.925710,0.001150,NaN,1319.000000,0.000000,0.000000
25%,42.000000,NaN,86955.000000,NaN,8.000000,0.000000,NaN,1.576510,0.505320,0.139050,NaN,1353.000000,0.000000,0.000000
50%,88.000000,NaN,118219.000000,NaN,15.000000,0.000000,NaN,2.153900,1.112870,0.185930,NaN,1386.000000,0.500000,0.000000
75%,134.000000,NaN,141163.000000,NaN,22.000000,0.000000,NaN,2.792350,1.735850,0.215000,NaN,1415.000000,1.000000,1.000000
max,180.000000,NaN,150780.000000,NaN,30.000000,1.000000,NaN,5.449120,11.142240,0.500000,NaN,1446.000000,1.000000,1.000000